### ISSUE TITLE
Please add support for Go 1.22

### ISSUE THREAD

**Issue by skitt** [containerbuildsystem/cachito#1001]
Kubernetes 1.30 and later requires Go 1.22 or later; any project pulling in corresponding k8s.io libraries needs Go 1.22.

**Comment by lkolacek** [comment]
Hi Stephen Kitt, we released partial support for Go 1.22. Can you confirm that you are unblocked now? If that's the case please close the issue. Thank you.

**Comment by akrejcir** [comment]
Hi, can you also add support for workspace vendoring?

One of our projects has multiple submodules, and using workspace vendoring allows us to have only one vendor directory.
When we try to build it we get an error:
```
Workspace vendoring introduced in Go 1.22 is not supported.
```

**Comment by skitt** [comment]
@lkolacek yes, cachito now works for us with Go 1.22.

**Comment by eskultety** [comment]
Reopening since workspace vendoring hasn't been implemented yet.

**Comment by eskultety** [comment]
> Reopening since workspace vendoring hasn't been implemented yet.

Please ignore this, the related issue https://github.com/containerbuildsystem/cachito/issues/1025 got closed with the reasoning that that work will not happen in cachito. Respecting that decision, I am closing this issue as well.
