### ISSUE TITLE
Enable golang workspace vendoring

### ISSUE THREAD

**Issue by akrejcir** [containerbuildsystem/cachito#1025]
Hi, can you add support for golang workspace vendoring?

One of our projects has multiple submodules, and using workspace vendoring allows us to have only one vendor directory.
When we try to build it we get an error:
```
Workspace vendoring introduced in Go 1.22 is not supported.
```

**Comment by lkolacek** [comment]
I apologize in advance but Cachito service is currently in the maintenance mode and we address only security fixes. Cachi2 CLI tool (successor of Cachito and part of the Konflux pipeline) will receive this feature.

**Comment by akrejcir** [comment]
Ok.
