### ISSUE TITLE
Make the GET API endpoints more efficient with SQL joins

### ISSUE THREAD

**Issue by mprahl** [containerbuildsystem/cachito#115]
The /requests GET API endpoint calls `to_json` on each the Request object returned by the pagination. Since no `joinedload` statements are provided as query options, SQLAlchemy will execute individual SELECT statements in the `to_json` method to expand those relationships. This can be improved by using joins on the initial paginated query.

This should also be improved on the /requests/<id> GET API endpoint as well.

Another project I've worked on does this. Here is an example of how this can be done:
https://github.com/release-engineering/iib/blob/610072591f79012da18704226271aa0c96c55242/iib/web/api_v1.py#L42
https://github.com/release-engineering/iib/blob/610072591f79012da18704226271aa0c96c55242/iib/web/models.py#L277-L306

**Comment by nirzari** [comment]
We don't seem to have performance issues with the mentioned endpoint. Bunch of other improvements have made Cachito DB operations much faster, close to 70% faster for large requests. @mprahl Would you be okay if we close the issue as we're not looking forward to a fix in the near future?

**Comment by mprahl** [comment]
Hey @nirzari, no concerns here if you want to close this.

**Comment by nirzari** [comment]
Thanks @mprahl.
Closing the issue based on the conversation above.
