### ISSUE TITLE
Valid response when parameter per_page=0

### ISSUE THREAD

**Issue by ejegrova** [containerbuildsystem/cachito#136]
You can use zero as an input for parameter per_page. This should most likely result in an error.
```

http://localhost:8080/api/v1/requests?per_page=0
{
  "items": [], 
  "meta": {
    "first": "http://localhost:8080/api/v1/requests?page=1&per_page=0", 
    "last": "http://localhost:8080/api/v1/requests?page=0&per_page=0", 
    "next": null, 
    "page": 1, 
    "pages": 0, 
    "per_page": 0, 
    "previous": null, 
    "total": 172
  }
}

```

**Comment by hluk** [comment]
But that could be handy to get item count without the actual data.

**Comment by lcarva** [comment]
> But that could be handy to get item count without the actual data.

That's a good point! If we do support `per_page=0`, then we should make sure the links and values under `meta` make sense.
