### ISSUE TITLE
Support Maven repositories

### ISSUE THREAD

**Issue by fabiendupont** [containerbuildsystem/cachito#629]
Many applications are written in Java and having a local cache of dependencies drastically improves the build time. Since Cachito is based on Nexus RepoManager 3, it should be possible to add support for Maven repositories: https://help.sonatype.com/repomanager3/nexus-repository-administration/formats/maven-repositories. Then, at build time, the `~/.m2/settings.xml` file could simply point to Cachito as a mirror.

**Comment by MartinBasti** [comment]
Can you please elaborate more about maven support?
Cachito is not supposed to be just a mirror, it does quite a lot information to provide details about dependencies, and mainly it's supposed to be used for sources.

**Comment by fabiendupont** [comment]
That's correct. Java applications will mainly reference binary dependencies.
Not being a Java developer, I am wondering if it is possible to specify a source repository for dependencies. If not, this issue is probably irrelevant.

**Comment by MartinBasti** [comment]
Closing as this is not the right usecase for cachito, cachito should process only sources.
